### PR TITLE
Save memory

### PR DESCRIPTION
**Pull request by marouenbg**
Hi @AndMastro,
I created a PR following your suggestion for the fix. Note the new branch called `save-memory` that I created from the devel branch. Please let me know if you have any comments.

### CODE REVIEW

**Comment by AndMastro** [comment]
Hi @marouenbg,
Thank you for clarifying this, I totally forgot to create the new branch.
No comments to add, thanks for the edit!

**Comment by marouenbg** [comment]
Hi @AndMastro ,

The unit tests failed again. I couldn't wrap my head around the issue. Could you please tell me more about the problem?

**Comment by AndMastro** [comment]
Hi @marouenbg,

I simply noticed that the panda output did not change regardless the value of `save_memory`. Either if you passed `save_memory=False` or `save_memory=True`, the output was saved as a matrix. This is because the `panda_network` attribute is always present. So, ` if hasattr(self,'panda_network')` will always return `True` and the network matrix will always be exported.
On the contrary, the attribute `export_panda_results` is present only when `save_memory` is `False`, as we see in line 381.  Thus, this allows us to save the ouput in the form **tf gene mofit force** when we call panda with `save_memory==False.`

I hope it was clear :)

**Comment by marouenbg** [comment]
Good catch @AndMastro I finally got what you mean. 
I used `unique_tfs` instead of `panda_network` but I implemented exactly the bug fix you suggested.
Thanks !

**Comment by AndMastro** [comment]
Hi @marouenbg,

Great, good news! Thank you!

**Pull request merged**
