### PR TITLE
Add mc p-val function for DRAGON

### PR DESCRIPTION
**Pull request by katehoffshutta**

### CODE REVIEW

**Comment by marouenbg** [comment]
addressing https://github.com/netZoo/netZooPy/issues/298

**Comment by violafanfani** [comment]
I have fixed the issues with the tests and pandas warnings. Update the branch to the current devel to have that fixed

**Comment by violafanfani** [comment]
@katehoffshutta looks like this works, should I squash and merge? Anything else to add before then?

**Comment by katehoffshutta** [comment]
Good to go from my end, thanks @violafanfani!

**Pull request merged**
