### PR TITLE
fix error when node labels where numbers

### PR DESCRIPTION
**Pull request by genisott**

### CODE REVIEW

**Comment by violafanfani** [comment]
Ehi @genisott, thanks for contributing. Did you pull the latest devel version before updating condor? I see there are conflicts and I am trying to understand what's the fix (all docstrings are different, so it is a bit confusing).

**Comment by genisott** [comment]
Hei,
I don't know how to fix the conflict. I changed two lines because there was
an error when the node labels were numbers and not strings.
I have already left for the day but I'll get around to fixing it either
this weekend or on Monday.

Sorry for the inconvenience 😬
Genís

fre. 4. mar. 2022, 16:21 skrev violafanfani ***@***.***>:

**Comment by violafanfani** [comment]
I think I managed to find them:
        cnames = self.net.columns
        self.net = self.net.astype({cnames[0]:str,cnames[1]:str})
You only added these, right?

**Comment by genisott** [comment]
Yes, also there was a self.net.columns =["V1","V2","weights"] that was
changed of place


fre. 4. mar. 2022, 16:32 skrev violafanfani ***@***.***>:

**Pull request merged**
