### PR TITLE
Added Pycondor and Pysambar

### PR DESCRIPTION
**Pull request by genisott**
I added the source files for Pycondor and Pysambar as they were in my packages. I haven't changed anything else.

### CODE REVIEW

**Comment by marouenbg** [comment]
Thanks Genis for this phenomenal contribution.

The packages were added as submodules because you kept your git versions.

Could you please `rm -rf .git` in both pysambar and pycondor.

Then `git add .` `git commit -m 'message'` and `git push origin new-feature`

**Comment by genisott** [comment]
I tried to do what you told me, I don't know if it worked though.

**Comment by marouenbg** [comment]
@genisott it did not push because I see no new commits. Make sure you are in new-feature branch through `git branch --list`, if it is not the case `git checkout new-feature` and try again.
if you are in new-feature make sure to `git push origin new-feature` I make the mistake of pushing to master all the time. Let me know if you have any error messages!

**Comment by genisott** [comment]
@marouenbg Hi! Sorry for my disappearance. I've been extremely busy and almost didn't touch my computer.
I tried doing what you said, changing the branch. I don't think it worked, in the sense that when I did push it said that all was up to date.
Should I start the whole process from scratch?

**Comment by marouenbg** [comment]
continued in #49

**Pull request closed without merging**
